- name: restart_logrotated
  systemd:
    name: logrotate
    state: restarted

- name: restart_systemd-journald
  systemd:
    name: systemd-journald
    state: restarted

- name: restart_docker
  systemd:
    name: docker
    state: restarted